name: "Feature Request"
description: "Suggest a new feature or enhancement."
title: "[Feature Request]_Title "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Please provide the following information:**

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the feature or enhancement in detail."
      placeholder: "Detailed description of the feature"

  - type: textarea
    id: rationale
    attributes:
      label: "Rationale"
      description: "Explain why this feature is needed."
      placeholder: "Why is this feature important?"

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution."
      placeholder: "Describe your solution."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "List any alternatives you've considered."
      placeholder: "Alternatives considered"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots."
      placeholder: "Additional context."

  - type: markdown
    attributes:
      value: |
        # impact assumptions

  - type: dropdown
    attributes:
      label: Severity
      description: Please specify the Severity of this PR on your Operation
      multiple: true
      options:
        - Not Severe
        - Low
        - Mid
        - High
        - Critical
        - Stopper
      
  - type: checkboxes
    attributes:
      label: Is there an existing issue with this?
      description: Please search to see if an issue with your feature request already exists.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Are there any labels you wish to add?
      description: Please search labels and identify those related to your feature request.
      options:
        - label: I have added the relevant labels to the feature request.
          required: true
