name: Proposal (Technical)
description: 'Propose a new implementation, tool, system, or feature.'
title: "[Proposal]_Title"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Description

  - type: textarea
    attributes:
      label: Summary
      description: A brief proposal summary, including the main goals and expected outcomes.

  - type: textarea
    attributes:
      label: Glossary of Terms
      description: Provide definitions and explanations of key terms used throughout the proposal. This ensures all readers have a common understanding of important concepts and terminology.

  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the project or feature, including background information, context, and its importance.
      
  - type: textarea
    attributes:
      label: Approval
      description: >
        What is needed for this to get approved?

        - **Reviews**: Who should review this? If unsure, consider people who often commit to the repo.
        - **Implementations**: Is this self-contained or does it affect external libraries/tools? If it affects others, consider creating a sample implementation.
        - **Acknowledgements**: Does this need acknowledgment from other tools/projects? List them here.
        - **Testing Progress**: What should the testing process look like? Include any automated or manual tests.

  - type: markdown
    attributes:
      value: |
        # User Stories

  - type: textarea
    attributes:
      label: User Stories
      description: |
        Describe scenarios illustrating how users are affected by the current problem and how the proposed solution will improve their experience. Example User Stories:

        - User Story 1: As a [type of user], I want [some goal] so that [some reason].
        - User Story 2: As a [type of user], I am facing [specific problem], which affects [aspect of the user's experience].

  - type: markdown
    attributes:
      value: |
        # Impact Assumptions

  - type: dropdown
    attributes:
      label: Assumed Complexity
      description: Specify the assumed complexity level.
      multiple: true
      options:
        - Hours
        - Days
        - Months
        - More than 1/2 Year

  - type: dropdown
    attributes:
      label: Impact Scale
      description: Specify the impact scale on other code/tools.
      multiple: true
      options:
        - No other tool
        - One more tool 
        - A few more tools
        - An entire tool group
        - Might propagate to all tools
        
  - type: textarea
    attributes:
      label: Other Tools Affected
      description: If the impact scale is anything but "No other tool," list all the tools/repos affected.

  - type: markdown
    attributes:
      value: |
        # Implementation Details

  - type: textarea
    attributes:
      label: How it Solves the Problem
      description: Explain how the proposed implementation addresses the initial problems.

  - type: textarea
    attributes:
      label: High-Level Overview
      description: Provide a brief outline of the proposed implementation and its key components.

  - type: textarea
    attributes:
      label: Detailed Technical Plan
      description: Describe the in-depth technical approach, including specific steps, methodologies, tools, and options considered for implementation.

  - type: textarea
    attributes:
      label: Unresolved Questions
      description: List all unresolved questions for further debate and consideration.

  - type: markdown
    attributes:
      value: |
        ## Steps and Milestones
      
  - type: textarea
    attributes:
      label: Milestones
      description: Provide key milestones to clarify the work steps for this proposal.

  - type: markdown
    attributes:
      value: |
        ## Dependencies and Problems

  - type: markdown
    attributes:
      value: |
        ### Problems

  - type: textarea
    attributes:
      label: Potential Problems
      description: Identify potential issues or challenges that may arise during implementation.

  - type: textarea
    attributes:
      label: Long-term Issues
      description: Identify any long-term issues that might emerge after implementation.

  - type: textarea
    attributes:
      label: Transient Problems
      description: Identify any temporary issues arising from implementing the proposed solution.

  - type: textarea
    attributes:
      label: Impacting Branches
      description: Detail any branches or repositories impacted by the project.

  - type: markdown
    attributes:
      value: |
        ### Dependencies

  - type: textarea
    attributes:
      label: Dependencies
      description: List all dependencies the project relies on, including software, hardware, and third-party services.

  - type: textarea
    attributes:
      label: Outgoing Dependencies
      description: List all projects, branches, and issues that rely on this implementation.

  - type: textarea
    attributes:
      label: Dependency Issues
      description: Identify any existing issues that might impact the project.

  - type: textarea
    attributes:
      label: Dependent Branches
      description: Detail any branches or repositories on which the project depends.

  - type: textarea
    attributes:
      label: Common Dependencies
      description: List any commonly used libraries, tools, or frameworks required for the project.

  - type: markdown
    attributes:
      value: |
        ## Testing and Documentation

  - type: textarea
    attributes:
      label: Non-persistent Tests
      description: Outline tests that can be run during development, including automated tests.

  - type: textarea
    attributes:
      label: Testing Plan
      description: Outline the strategy for testing the project, including unit, integration, and user acceptance tests.

  - type: textarea
    attributes:
      label: Documentation
      description: Describe the documentation to be created or updated as part of this project.

  - type: markdown
    attributes:
      value: |
        ## Maintenance

  - type: textarea
    attributes:
      label: Maintenance
      description: Explain the plan for maintaining the project after implementation.

  - type: textarea
    attributes:
      label: Risk Management
      description: Identify potential risks and provide a mitigation plan for each.

  - type: textarea
    attributes:
      label: Appendices
      description: Include any additional information, diagrams, or references supporting the proposal.

  - type: checkboxes
    attributes:
      label: Existing Issues
      description: >-
        Please search to see if an issue with this proposal already exists.
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    attributes:
      label: Relevant Labels
      description: Please add relevant labels to the proposal.
      options:
        - label: I have added the relevant labels to the proposal.
          required: true
