# -*- coding: utf-8 -*-
"""Package declaring ayon_usd addon version.

Version is regenerated by `create_package.py` script or the
build system based on the content of package.py.

Do not manually edit this file.
"""
__version__ = "ayon_usd"
