# -*- coding: utf-8 -*-
"""Package declaring ayon_usd addon version.

Version is regenerated by `create_package.py` script or the
build system based on the content of package.py.

Do not manually edit this file.
"""
name = "ayon_usd"
__version__ = "1.0.25-LR"
